# Source: https://docs.docker.com/build/ci/github-actions/multi-platform/
# hello
name: Build and push image to Docker Hub

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: andi4000/trmnlp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Ruby Version
        run: echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            RUBY_VERSION=${{ env.RUBY_VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}-buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}-buildcache,mode=max
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
